### ISSUE TITLE
Problem when creating diagram

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#12]
I have the following text:

    
    #!dot
    
    diagram G { 
            comganzttuserserviceBindVillageSvc [ label = " 
                    \n  
                    BindVillageSvc\n
                    --------------------------\n
                    this is a very long text that was wroten by shekespare becuase he...
                "    
            ]    
    
            comganzttuserserviceBindVillageSvc -> comganzgsfserviceLocalService [label = "Extends"];
    }
    
    

but when running the command:
    
    #!bash
    
    blockdiag pepe.diag
    

I get the following exception:
    
    #!python
    
    Traceback (most recent call last):
      File "/home/tzulberti/envs/uml/bin/blockdiag", line 9, in <module>
        load_entry_point('blockdiag==0.7.8', 'console_scripts', 'blockdiag')()
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/blockdiag.py", line 623, in main
        draw.draw()
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/DiagramDraw.py", line 105, in draw
        self.node(node, **kwargs)
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/DiagramDraw.py", line 240, in node
        font=self.font, badgeFill=self.badgeFill)
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/noderenderer/__init__.py", line 54, in render
        self.render_label(drawer, **kwargs)
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/noderenderer/__init__.py", line 68, in render_label
        lineSpacing=self.metrix.lineSpacing)
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/ImageDrawEx.py", line 251, in textarea
        lines = TextFolder(box, string, scale=self.scale_ratio, **kwargs)
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/utils/PILTextFolder.py", line 23, in __init__
        TextFolder.__init__(self, box, string, **kwargs)
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/utils/TextFolder.py", line 88, in __init__
        self._result = self._lines()
      File "/home/tzulberti/envs/uml/lib/python2.6/site-packages/blockdiag-0.7.8-py2.6.egg/blockdiag/utils/TextFolder.py", line 183, in _lines
        if size[1] < height + metrics[1]:
    UnboundLocalError: local variable 'metrics' referenced before assignment
    

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/6
- Originally reported by: Tomas Zulberti
- Originally created at: 2011-04-26T02:48:32.012

**Comment by tk0miya** [comment]
_From Tomas Zulberti on 2011-04-26 00:56:45+00:00_

I think that the error might be related to the length of the text or to the new lines in the label. 

If I use the following text:
{{{
#!dot

diagram G { 
        comganzttuserserviceBindVillageSvc [ label = "a\n
                \n
                BindVillageSvc\n
                --------------------------\n
                this is a very long text that was wroten by shekespare becuase he...
            "    
        ]    

        comganzttuserserviceBindVillageSvc -> comganzgsfserviceLocalService [label = "Extends"];
}

}}}

There is no exception, and an image is created but not all the text appears (maybe becuase I didn't set the size). If I don't put the **a** before **a\n** and leave only **\n** in the first line, the exception take place.

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2011-04-26 04:27:56+00:00_

I found more shorten example about this problem:

{
  A [label = " "];
}

This problem is caused by spaces only line.
I'll fix it soon

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2011-04-26 07:18:53+00:00_

 * Fix #6; errors with spaces only label
 * Add doctests

→ \<\<cset f12f3ccf041de17431527d9f5692c9af86f6a3c5\>\>
