### ISSUE TITLE
ERROR: 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [blockdiag/blockdiag#178]
blockdiag sample.diag

ERROR: 'FreeTypeFont' object has no attribute 'getsize'

installed

freetype_py-2.4.0-py3-none-macosx_10_9_universal2.whl
Pillow==9.5.0 or Pillow==10.0.0

**Comment by ViktorHaag** [comment]
I see this problem when trying to use Pillow 10.0.0, but not with Pillow 9.5.0 (on MacOS). However, I'm using free type as installed via homebrew (installed version 2.13.1), so it's possible that this difference is meaningful?

(My environment: MacOS 13.5/Intel, Pillow 9.5.0, Sphinx 7.1.2, blockdiag 3.0.0, freetype 2.13.1 via homebrew)

**Comment by ViktorHaag** [comment]
See also: issue #176; perhaps we should close this one?

**Comment by ShaheedHaque** [comment]
Unfortunately for me, the workaround of "pillow<10" produces this result on a freshly upgraded Ubuntu 25.04:

```
$ pip install ...
Collecting pillow<10 (from paiyroll==2025.1)
  Using cached Pillow-9.5.0.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/home/srhaque/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/srhaque/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/srhaque/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-lidffw2n/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-lidffw2n/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-lidffw2n/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-lidffw2n/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 29, in <module>
        File "<string>", line 26, in get_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I tried forcing the code in ImageFont.py to avoid the use of `getsize()`, but then ran into https://github.com/blockdiag/blockdiag/issues/176#issuecomment-1903860109. I confess to being at a loss as to how to debug this (i.e. the `KeyError: '__version__'`) further. Any hints or fixes appreciated.

**Comment by ShaheedHaque** [comment]
Never mind, I forgot I had already been been down this path... https://github.com/blockdiag/blockdiag/pull/179#issuecomment-2196130973 leads to https://github.com/yuzutech/blockdiag/pull/9
