### ISSUE TITLE
blockdiag-0.8.9: AttributeError: 'ImageDrawEx' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#18]
with 
blockdiag-0.8.9-py2.7.egg
sphinxcontrib_blockdiag-0.9.0-py2.7.egg

using the example in the sphinx-docs
.. blockdiag::

    diagram admin {
      top_page -> config -> config_edit -> config_confirm  -> top_page;
    }

results in following traceback:

# Sphinx version: 1.0.7
# Python version: 2.7.2
# Docutils version: 0.8 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/opt/dev/sphinx/lib/python2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/cmdline.py", line 188, in main
    app.build(force_all, filenames)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/opt/dev/sphinx/lib/python2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/builders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/opt/dev/sphinx/lib/python2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/builders/__init__.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/builders/__init__.py", line 294, in write
    self.write_doc(docname, doctree)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/builders/html.py", line 408, in write_doc
    self.docwriter.write(doctree, destination)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/docutils-0.8-py2.7.egg/docutils/writers/__init__.py", line 77, in write
    self.translate()
  File "/opt/dev/sphinx/lib/python2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/docutils-0.8-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/opt/dev/sphinx/lib/python2.7/site-packages/docutils-0.8-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/opt/dev/sphinx/lib/python2.7/site-packages/docutils-0.8-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/opt/dev/sphinx/lib/python2.7/site-packages/docutils-0.8-py2.7.egg/docutils/nodes.py", line 165, in walkabout
    visitor.dispatch_visit(self)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/docutils-0.8-py2.7.egg/docutils/nodes.py", line 1604, in dispatch_visit
    return method(node)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/sphinxcontrib_blockdiag-0.9.0-py2.7.egg/sphinxcontrib/blockdiag.py", line 298, in html_visit_blockdiag
    render_dot_html(self, node, node['code'], node['options'])
  File "/opt/dev/sphinx/lib/python2.7/site-packages/sphinxcontrib_blockdiag-0.9.0-py2.7.egg/sphinxcontrib/blockdiag.py", line 196, in render_dot_html
    image.save()
  File "/opt/dev/sphinx/lib/python2.7/site-packages/blockdiag-0.8.9-py2.7.egg/blockdiag/DiagramDraw.py", line 283, in save
    return self.drawer.save(self.filename, size, self.format)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/blockdiag-0.8.9-py2.7.egg/blockdiag/imagedraw/filters/linejump.py", line 158, in save
    self._run()
  File "/opt/dev/sphinx/lib/python2.7/site-packages/blockdiag-0.8.9-py2.7.egg/blockdiag/imagedraw/filters/linejump.py", line 89, in _run
    method(self.target, *args, **kwargs)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/blockdiag-0.8.9-py2.7.egg/blockdiag/imagedraw/png.py", line 280, in textarea
    self.text(xy, string, **kwargs)
  File "/opt/dev/sphinx/lib/python2.7/site-packages/blockdiag-0.8.9-py2.7.egg/blockdiag/imagedraw/png.py", line 251, in text
    size = self.textsize(string)
AttributeError: 'ImageDrawEx' object has no attribute 'textsize'

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/12
- Originally reported by: Wouter Vanden Hove
- Originally created at: 2011-08-09T16:53:40.462

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2011-08-10 11:47:59+00:00_

I fixed it at rev.887
