### ISSUE TITLE
pip3 install issue

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#60]
I get an error on a pip3 package install (Ubuntu 13.10)

```
Downloading/unpacking blockdiag
  Downloading blockdiag-1.3.3.tar.gz (137kB): 137kB downloaded
  Running setup.py egg_info for package blockdiag
    
Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib/python3/dist-packages (from blockdiag)
Downloading/unpacking funcparserlib (from blockdiag)
  Downloading funcparserlib-0.3.6.tar.gz
  Running setup.py egg_info for package funcparserlib
    
    warning: no files found matching 'requires.txt'
Downloading/unpacking webcolors (from blockdiag)
  Downloading webcolors-1.4.tar.gz
  Running setup.py egg_info for package webcolors
    
Downloading/unpacking Pillow (from blockdiag)
  Downloading Pillow-2.4.0.zip (6.5MB): 6.5MB downloaded
  Running setup.py egg_info for package Pillow
    
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1062, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 371, in assert_source_matches_version
    version = self.installed_version
  File "/usr/lib/python3/dist-packages/pip/req.py", line 367, in installed_version
    return self.pkg_info()['version']
  File "/usr/lib/python3/dist-packages/pip/req.py", line 334, in pkg_info
    data = self.egg_info_data('PKG-INFO')
  File "/usr/lib/python3/dist-packages/pip/req.py", line 274, in egg_info_data
    data = fp.read()
  File "/usr/lib/python3.3/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1977: ordinal not in range(128)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/54
- Originally reported by: [psychemedia](https://bitbucket.org/psychemedia)
- Originally created at: 2014-05-08T13:06:06.793

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-05-09 09:57:16+00:00_

It caused from pip's bug.
Please update your pip3 with `sudo pip3 install --upgrade pip`.
And then, you can install them.

FYI: http://stackoverflow.com/questions/20995574/cannot-install-pil-due-to-a-unicodedecodeerror

**Comment by tk0miya** [comment]
_From [psychemedia](https://bitbucket.org/psychemedia) on 2014-05-09 13:16:47+00:00_

My mistake... sorry.. thought I'd done those checks.. Thanks anyway:-)
