### ISSUE TITLE
FAIL: blockdiag.tests.test_generate_diagram.test_generate

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#67]
Another issue produced with `tox` on Windows:
```
FAIL: blockdiag.tests.test_generate_diagram.test_generate(<function main at
0x03225CD8>, 'svg',
'E:\\p\\blockdiag\\src\\blockdiag\\tests\\diagrams\\node_icon.diag', [])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\p\blockdiag\.tox\py34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "E:\p\blockdiag\src\blockdiag\tests\utils.py", line 68, in wrap
    raise AssertionError('Caught error')
nose.proxy.AssertionError: Caught error
-------------------- >> begin captured stdout << ---------------------
---[ stderr ] ---
WARNING: icon image not found: /usr/share/pixmaps/debian-logo.png
WARNING: Could not retrieve: http://blockdiag.com/favicon.ico
Traceback (most recent call last):
  File "E:\p\blockdiag\src\blockdiag\utils\images.py", line 116, in open
    stream = io.BytesIO(urlopen(url).read())
  File "E:\p\blockdiag\src\blockdiag\utils\images.py", line 38, in urlopen
    return io.open(urlopen_cache[url].name, 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\...\\Temp\\tmp2kj_gnoh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\p\blockdiag\src\blockdiag\utils\bootstrap.py", line 39, in run
    return self.build_diagram(parsed)
  File "E:\p\blockdiag\src\blockdiag\command.py", line 42, in build_diagram
    return super(BlockdiagApp, self).build_diagram(tree)
  File "E:\p\blockdiag\src\blockdiag\utils\bootstrap.py", line 84, in build_diagram
    drawer.draw()
  File "E:\p\blockdiag\src\blockdiag\drawer.py", line 88, in draw
    self._draw_background()
  File "E:\p\blockdiag\src\blockdiag\drawer.py", line 114, in _draw_background
    shape = r(node, self.metrics)
  File "E:\p\blockdiag\src\blockdiag\noderenderer\base.py", line 33, in __init__
    image_size = images.get_image_size(node.icon)
  File "E:\p\blockdiag\src\blockdiag\utils\images.py", line 47, in get_image_size
    stream = open(image)
  File "E:\p\blockdiag\src\blockdiag\utils\images.py", line 119, in open
    raise IOError
OSError
```

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/61
- Originally reported by: anatoly techtonik
- Originally created at: 2014-10-31T13:19:54.451

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-01 02:30:17+00:00_

Fix #61 images.urlopen() got PermissionError on Windows

On windows environment, NamedTemporaryFile causes PermissionError
because it keeps file opening. Windows does not accept double opening files.

→ \<\<cset d01a0b34cf24c21b87300ad95ddb6685852ce8af\>\>

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-01 02:31:29+00:00_

[anatoly techtonik](https://bitbucket.org/techtonik) The change at f10960d would resolve the problem. but I don't have windows environment. Could you try it please?

**Comment by tk0miya** [comment]
_From anatoly techtonik on 2014-11-01 07:46:06+00:00_

Yes, Windows is less forgiving to open files. But the test doesn't pass yet:

```
---[ stderr ] ---
WARNING: unknown image type: http://upload.wikimedia.org/wikipedia/commons/9/9b/Scalable_Vector_Graphics_Circle2.svg
Traceback (most recent call last):
  File "E:\p\blockdiag\src\blockdiag\utils\bootstrap.py", line 40, in run
    return self.build_diagram(parsed)
  File "E:\p\blockdiag\src\blockdiag\command.py", line 42, in build_diagram
    return super(BlockdiagApp, self).build_diagram(tree)
  File "E:\p\blockdiag\src\blockdiag\utils\bootstrap.py", line 91, in build_diagram
    drawer.save()
  File "E:\p\blockdiag\src\blockdiag\drawer.py", line 187, in save
    return self.drawer.save(self.filename, size, self.format)
  File "E:\p\blockdiag\src\blockdiag\imagedraw\filters\linejump.py", line 171, in save
    self._run()
  File "E:\p\blockdiag\src\blockdiag\imagedraw\filters\linejump.py", line 98, in _run
    method(self.target, *args, **kwargs)
  File "E:\p\blockdiag\src\blockdiag\imagedraw\svg.py", line 246, in image
    stream = images.open(url, mode='png')
  File "E:\p\blockdiag\src\blockdiag\utils\images.py", line 136, in open
    image.save(png_image, 'PNG')
  File "E:\p\blockdiag\.tox\py27\lib\site-packages\PIL\Image.py", line 1653, in save
    self.load()
  File "E:\p\blockdiag\.tox\py27\lib\site-packages\PIL\EpsImagePlugin.py", line 336, in load
    self.im = Ghostscript(self.tile, self.size, self.fp, scale)
  File "E:\p\blockdiag\.tox\py27\lib\site-packages\PIL\EpsImagePlugin.py", line 137, in Ghostscript
    raise WindowsError('Unable to locate Ghostscript on paths')
WindowsError: Unable to locate Ghostscript on paths
```

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-02 02:27:10+00:00_

Fix #61 images.open() raises exception if ghostscript not found

→ \<\<cset 55721e3a4fb3b4bace9c523658591a8139f74500\>\>

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-02 02:30:01+00:00_

Hi, [anatoly techtonik](https://bitbucket.org/techtonik)

I fix it again at d0c18b8. Could you try this please?

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-02 11:35:54+00:00_

Thanks a lot!

>All ok. How to get what tests were skipped?

They are slow testcases. They are only enabled on CI server.

Setting `NOSE_VERBOSE=2` as environment variable will let you know what tests are skipped.

**Comment by tk0miya** [comment]
_From anatoly techtonik on 2014-11-02 15:52:37+00:00_

No problem.

It says that `Pillow` and `reportlab` are missing. Why `tox` doesn't install them? They are listed both in `setup.py` and in `tox.ini`

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-04 03:40:01+00:00_

Sorry, I inestigated. The messages were wrong.

Those tests needs truetype font placed at `src/blockdiag/tests/truetype/VL-PGothic-Regular.ttf`.
At drone.io, the font is copied before running tests.

I noticed this behavior is very unkind. I would improve it better.

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-15 06:57:11+00:00_

Finally, I bundled the font file into the archive. and the heavy tests are invoked with `ALL_TESTS=1` environment variable.

**Comment by tk0miya** [comment]
_From anatoly techtonik on 2014-11-15 10:10:06+00:00_

Sounds good. How heavy are the heavy tests? )

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2014-11-15 15:50:30+00:00_

There is a 9-10 times difference in those.

```
$ tox -e py27
...
Ran 711 tests in 11.372s

OK (SKIP=351)
```

```
$ ALL_TESTS=1 tox -e py27
...
Ran 711 tests in 101.866s

OK
```
