### ISSUE TITLE
rotate not working with pillow 3.0.0 and png output

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/blockdiag#78]
It seems the "rotate" option is broken when used with pillow 3.0.0.

If I try to compile the following packet.diag to an png PIL throws an exception.

```packetdiag packet.diag --debug```

If I convert the code to SVG it is working.

```packetdiag packet.diag --debug -T svg```

I want to use it within sphinx but it seems sphinxcontrib-nwdiag does not accept my configuration option ```nwdiag_html_image_format = "SVG"``` and fails with the same error.

It looks like a problem like this one: http://stackoverflow.com/questions/20297659/why-does-pil-fail-to-merge-2-images-in-my-code
```
{
    colwidth = 16
    node_height = 72
    node_width = 14
    scale_interval = 8
    0-7:   test
    8-15:  test1 [color=green, rotate=270]
}
```

```
#!python

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\blockdiag\utils\bootstrap.py", line 54, in run
    return self.build_diagram(parsed)
  File "C:\Python27\lib\site-packages\blockdiag\utils\bootstrap.py", line 107, in build_diagram
    drawer.save()
  File "C:\Python27\lib\site-packages\blockdiag\drawer.py", line 187, in save
    return self.drawer.save(self.filename, size, self.format)
  File "C:\Python27\lib\site-packages\blockdiag\imagedraw\filters\linejump.py", line 181, in save
    self._run()
  File "C:\Python27\lib\site-packages\blockdiag\imagedraw\filters\linejump.py", line 108, in _run
    method(self.target, *args, **kwargs)
  File "C:\Python27\lib\site-packages\blockdiag\imagedraw\png.py", line 338, in textarea
    self.paste(filler, box.topleft, text._image.rotate(angle))
  File "C:\Python27\lib\site-packages\blockdiag\imagedraw\png.py", line 137, in paste
    self._image.paste(image, pt, mask)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1319, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match

```

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/blockdiag/issue/72
- Originally reported by: Florian Zierer
- Originally created at: 2015-12-22T14:05:52.972

**Comment by ncoghlan** [comment]
Checking the code, it looks to me like this may just be a docs bug: even though they're part of the nwdiag plugin, packetdiag and rackdiag still have their own config settings.

**Comment by ncoghlan** [comment]
This is what I just set up in `conf.py` to ensure I have consistent settings across all the diagram plugins:

```
def _enable_blockdiag_plugins(config):
    plugins = [
        "actdiag",
        "blockdiag",
        "nwdiag",
        "packetdiag", # part of nwdiag
        "rackdiag", # part of nwdiag
        "seqdiag",
    ]
    settings = {
        "fontpath": "/usr/share/fonts/truetype/ipafont/ipagp.ttf",
        "html_image_format": "SVG",
        "debug": True
    }
    extensions = config["extensions"]
    for plugin in plugins:
        extensions.append("sphinxcontrib." + plugin)
        for suffix, value in settings.items():
            setting = plugin + "_" + suffix
            config[setting] = value

_enable_blockdiag_plugins(globals())
```

**Comment by ncoghlan** [comment]
It seems the "Use SVG instead" workaround runs into problems when trying to produce a PDF via `latexpdf`, since the LaTeX builder doesn't handle SVGs :(

**Comment by rolfsrolfs** [comment]
`ERROR: images do not match` happens when trying to create png files where part of the diagram has a rotate tag.
Downgrading Pillow fixes this. Try this:
`$ sudo pip install Pillow==2.9.0`
nwdiag/packetdiag fails to utilize the newer version of Pillow, so it fails to handle rotate parts.
