### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by dridi** [blockdiag/blockdiag#93]
This is related to blockdiag/seqdiag#24, once I get seqdiag to compile with Python 3.7 I get a failure in its test suite:

```
ERROR: test_setup_inline_svg_is_true_but_format_isnt_svg (test_rst_directives.TestRstDirectives)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/myitertools.py", line 41, in stepslice
    next(iterable)
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-seqdiag-0.9.5-14.fc29/src/seqdiag/tests/test_rst_directives.py", line 166, in test_setup_inline_svg_is_true_but_format_isnt_svg
    doctree = publish_doctree(text)
  File "/usr/lib/python3.7/site-packages/docutils/core.py", line 481, in publish_doctree
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/rst/directives.py", line 54, in decorator
    return fn(*args)
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/rst/directives.py", line 178, in run
    results[0] = self.node2image(node, diagram)
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/rst/directives.py", line 254, in node2image
    drawer.save()
  File "/usr/lib/python3.7/site-packages/blockdiag/drawer.py", line 187, in save
    return self.drawer.save(self.filename, size, self.format)
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/filters/linejump.py", line 181, in save
    self._run()
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/filters/linejump.py", line 108, in _run
    method(self.target, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 217, in line
    self.dashed_line(xy, **kwargs)
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 230, in dashed_line
    for subline in dashize_line(line, cycle):
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 61, in dashize_line
    for y1, y2 in istep(n for n in r):
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/myitertools.py", line 22, in istep
    yield [next(iterable) for _ in range(step)]
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/myitertools.py", line 22, in <listcomp>
    yield [next(iterable) for _ in range(step)]
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 61, in <genexpr>
    for y1, y2 in istep(n for n in r):
RuntimeError: generator raised StopIteration
----------------------------------------------------------------------
Ran 88 tests in 0.964s
FAILED (errors=1, skipped=33)
```

Looking at `myitertools.py` and [PEP 479](https://www.python.org/dev/peps/pep-0479/) I'm not sure what the best course of action is to fix this.

**Comment by serhiy-storchaka** [comment]
For istep():
```python
from itertools import islice
def istep(seq, step=2):
    it = iter(seq)
    while True:
        item = list(islice(it, step))
        yield item
        if len(item) < step:
            break
```
As for stepslice(), it may be simpler to wrap the body in:
```python
try:
    ...
except StopIteration:
    return
```

**Comment by tk0miya** [comment]
Good point! Could you send me the patch as a PR?

**Comment by dridi** [comment]
With this change I get a different failure in the seqdiag test suite:

```
ERROR: test_setup_inline_svg_is_true_but_format_isnt_svg (test_rst_directives.TestRstDirectives)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/seqdiag-0.9.5/src/seqdiag/tests/test_rst_directives.py", line 166, in test_setup_inline_svg_is_true_but_format_isnt_svg
    doctree = publish_doctree(text)
  File "/usr/lib/python2.7/site-packages/docutils/core.py", line 481, in publish_doctree
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python2.7/site-packages/blockdiag/utils/rst/directives.py", line 54, in decorator
    return fn(*args)
  File "/usr/lib/python2.7/site-packages/blockdiag/utils/rst/directives.py", line 178, in run
    results[0] = self.node2image(node, diagram)
  File "/usr/lib/python2.7/site-packages/blockdiag/utils/rst/directives.py", line 254, in node2image
    drawer.save()
  File "/usr/lib/python2.7/site-packages/blockdiag/drawer.py", line 187, in save
    return self.drawer.save(self.filename, size, self.format)
  File "/usr/lib/python2.7/site-packages/blockdiag/imagedraw/filters/linejump.py", line 181, in save
    self._run()
  File "/usr/lib/python2.7/site-packages/blockdiag/imagedraw/filters/linejump.py", line 108, in _run
    method(self.target, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/blockdiag/imagedraw/png.py", line 217, in line
    self.dashed_line(xy, **kwargs)
  File "/usr/lib/python2.7/site-packages/blockdiag/imagedraw/png.py", line 230, in dashed_line
    for subline in dashize_line(line, cycle):
  File "/usr/lib/python2.7/site-packages/blockdiag/imagedraw/png.py", line 61, in dashize_line
    for y1, y2 in istep(n for n in r):
ValueError: need more than 1 value to unpack
----------------------------------------------------------------------
Ran 88 tests in 4.051s
FAILED (errors=1, skipped=33)
```

**Comment by serhiy-storchaka** [comment]
> Could you send me the patch as a PR?

Sorry, I'm not a user of blockdiag. I just searched for Python 3.7 incompatibilities.

> With this change I get a different failure in the seqdiag test suite:

Ah, the original `istep()` ignored incomplete chuncks! Then either move `yield item` to the end of the loop, or wrap the body of the original `istep()` with:
```python
try:
    ...
except StopIteration:
    return
```

**Comment by dridi** [comment]
I thought of moving the `yield` statement after the conditional break but didn't have time to test it. I will give it a try, thanks.

**Comment by dridi** [comment]
I have successfully rebuilt blockdiag and the other \*diag (that depend on blockdiag at build time) with Python 3.7 and haven't experienced any problem as far as the test suites go. I can submit a pull request on behalf of @serhiy-storchaka if you prefer with the patch I used for Fedora 29.
