### ISSUE TITLE
python bootstrap.py is not compatible with setuptools >= 39.0.0

### ISSUE THREAD

**Issue by ggrossetie** [blockdiag/blockdiag#97]
```
# pip install setuptools==39.0.0
Collecting setuptools==39.0.0
  Downloading https://files.pythonhosted.org/packages/26/57/69f35fa2ee411cfa3557efa40f776992dffb54d8edd52e03ec0be5fb3bb9/setuptools-39.0.0-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 24.5MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 38.0.0
    Uninstalling setuptools-38.0.0:
      Successfully uninstalled setuptools-38.0.0
Successfully installed setuptools-39.0.0
```
```
root@a9b4cc608975:/blockdiag# python bootstrap.py 
2.13.0
Traceback (most recent call last):
  File "bootstrap.py", line 137, in <module>
    if _final_version(distv):
  File "bootstrap.py", line 123, in _final_version
    for part in parsed_version:
TypeError: 'Version' object is not iterable
```
```
root@a9b4cc608975:/blockdiag# pip install setuptools==38.0.0
Collecting setuptools==38.0.0
  Using cached https://files.pythonhosted.org/packages/54/60/54e7ee235b377854f8ccaec996ccae04c33f59eb86c44c387761a82cafea/setuptools-38.0.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 39.0.0
    Uninstalling setuptools-39.0.0:
      Successfully uninstalled setuptools-39.0.0
Successfully installed setuptools-38.0.0
```
```
root@a9b4cc608975:/blockdiag# python bootstrap.py
```

**Comment by ggrossetie** [comment]
```
/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py:208: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version.
This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0.
In most cases, conversion to a tuple is unnecessary.
For comparison of versions, sort the Version instances directly.
If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
```

**Comment by tk0miya** [comment]
It's time to say good-bye to buildout...

**Comment by tk0miya** [comment]
Removed in #103

**Comment by ggrossetie** [comment]
Thanks @tk0miya 👍 

Just to let you know, I'm using BlockDiag, SeqDiag, ActDiag and NwDiag at https://kroki.io/
Eg: https://demo.kroki.io/blockdiag/svg/eNpdzEEKgzAQheF9TjFm7wmKXkRcTO0jBGNGJqUllN5dowuDy8f_8cwzyDS_PDv6GbpG25NDhPIbqQx7pLY05SXZxw37U32gmcApN7uoyTBJEKWOrFMgZoQgXzvuN_fniq4-zqepfqsuytGhiL_ZAMihQIU=

**Comment by tk0miya** [comment]
Cool!
