### ISSUE TITLE
Python 3 test failure in test_setup_inline_svg_is_true_with_multibytes

### ISSUE THREAD

**Issue by jayvdb** [blockdiag/blockdiag#99]
Running the tests on openSUSE packaging systems, all platforms fail on Python 3 with

```console
[   22s] ======================================================================
[   22s] ERROR: test_setup_inline_svg_is_true_with_multibytes (blockdiag.tests.rst.test_blockdiag_directives.TestRstDirectives)
[   22s] ----------------------------------------------------------------------
[   22s] Traceback (most recent call last):
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/tests/rst/test_blockdiag_directives.py", line 189, in test_setup_inline_svg_is_true_with_multibytes
[   22s]     doctree = publish_doctree(text)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/core.py", line 481, in publish_doctree
[   22s]     output = pub.publish(enable_exit_status=enable_exit_status)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
[   22s]     self.settings)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
[   22s]     self.parse()
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
[   22s]     self.parser.parse(self.input, document)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
[   22s]     self.statemachine.run(inputlines, document, inliner=self.inliner)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
[   22s]     input_source=document['source'])
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
[   22s]     context, state, transitions)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
[   22s]     return method(match, context, next_state)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
[   22s]     nodelist, blank_finish = self.explicit_construct(match)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
[   22s]     return method(self, expmatch)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
[   22s]     directive_class, match, type_name, option_presets)
[   22s]   File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
[   22s]     result = directive_instance.run()
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/utils/rst/directives.py", line 54, in decorator
[   22s]     return fn(*args)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/utils/rst/directives.py", line 178, in run
[   22s]     results[0] = self.node2image(node, diagram)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/utils/rst/directives.py", line 254, in node2image
[   22s]     drawer.save()
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/drawer.py", line 187, in save
[   22s]     return self.drawer.save(self.filename, size, self.format)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/filters/linejump.py", line 181, in save
[   22s]     self._run()
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/filters/linejump.py", line 108, in _run
[   22s]     method(self.target, *args, **kwargs)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/svg.py", line 135, in textarea
[   22s]     lines = self.textfolder(box, string, font, **kwargs)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/textfolder.py", line 66, in get
[   22s]     return HorizontalTextFolder(*args, **kwargs)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/textfolder.py", line 208, in __init__
[   22s]     self._result = self._lines()
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/textfolder.py", line 285, in _lines
[   22s]     for folded in splittext(self, line, maxwidth, measure):
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/textfolder.py", line 41, in splittext
[   22s]     textsize = metrics.textsize(text[0:i])
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/textfolder.py", line 212, in textsize
[   22s]     textsize = self.drawer.textlinesize(text, self.font)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/utils/__init__.py", line 65, in func
[   22s]     fn.cache[key] = fn(*args, **kwargs)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/svg.py", line 115, in textlinesize
[   22s]     return self._pil_drawer.textlinesize(string, font)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/utils/__init__.py", line 65, in func
[   22s]     fn.cache[key] = fn(*args, **kwargs)
[   22s]   File "/home/abuild/rpmbuild/BUILD/blockdiag-1.5.4/src/blockdiag/imagedraw/png.py", line 282, in textlinesize
[   22s]     size = self.draw.textsize(string, font=None)
[   22s]   File "/usr/lib64/python3.7/site-packages/PIL/ImageDraw.py", line 318, in textsize
[   22s]     return font.getsize(text, direction, features)
[   22s]   File "/usr/lib64/python3.7/site-packages/PIL/ImageFont.py", line 112, in getsize
[   22s]     return self.font.getsize(text)
[   22s] UnicodeEncodeError: 'latin-1' codec can't encode character '\u3042' in position 0: ordinal not in range(256)
[   22s] -------------------- >> begin captured logging << --------------------
[   22s] PIL.PngImagePlugin: DEBUG: STREAM b'IHDR' 16 13
[   22s] PIL.PngImagePlugin: DEBUG: STREAM b'IDAT' 41 1216
[   22s] --------------------- >> end captured logging << ---------------------
```

See https://build.opensuse.org/package/show/home:jayvdb:noflake8/python-blockdiag for the .spec and complete logs for lots of build environments.

Those environments include Python 3.4 and 3.6 and 3.7.

The tests always pass on Python 2.7 .

**Comment by fredcadete** [comment]
I have the same issue, though both in 2.7 and 3.7.

I believe the root cause is in Pillow not having font information, and using a default font that is not CJK-capable (the failing tests is using hiragana). Here is a related Pillow issue: https://github.com/python-pillow/Pillow/issues/3878 

The issue goes away if I hardcode the load of a NotoSans-Regular.ttf in ttfont_for() (src/blockdiag/imagedraw/png.py) .

I suppose the correct fix would be for the blockdiag tests to configure Pillow with a font with CJK support, but I actually don't know how that would be done.
